#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

. /lib/functions.sh

usage() {
	cat <<EOF
Usage: $0 [down|detect]
enables (default), disables or detects a wifi configuration.
EOF
	exit 1
}

find_net_config() {(
	local vif="$1"
	local cfg
	local ifname

	config_get cfg "$vif" network

	[ -z "$cfg" ] && {
		include /lib/network
		scan_interfaces

		config_get ifname "$vif" ifname

		cfg="$(find_config "$ifname")"
	}
	[ -z "$cfg" ] && return 0
	echo "$cfg"
)}


bridge_interface() {(
	local cfg="$1"
	[ -z "$cfg" ] && return 0

	include /lib/network
	scan_interfaces

	for cfg in $cfg; do
		config_get iftype "$cfg" type
		[ "$iftype" = bridge ] && config_get "$cfg" ifname
		prepare_interface_bridge "$cfg"
		return $?
	done
)}

wifi_fixup_hwmode() {
	local device="$1"
	local default="$2"
	local hwmode hwmode_11n

	config_get channel "$device" channel
	config_get hwmode "$device" hwmode
	case "$hwmode" in
		11bg) hwmode=bg;;
		11a) hwmode=a;;
		11b) hwmode=b;;
		11g) hwmode=g;;
		11n*)
			hwmode_11n="${hwmode##11n}"
			case "$hwmode_11n" in
				a|g) ;;
				default) hwmode_11n="$default"
			esac
			config_set "$device" hwmode_11n "$hwmode_11n"
		;;
		*)
			hwmode=
			if [ "${channel:-0}" -gt 0 ]; then 
				if [ "${channel:-0}" -gt 14 ]; then
					hwmode=a
				else
					hwmode=g
				fi
			else
				hwmode="$default"
			fi
		;;
	esac
	config_set "$device" hwmode "$hwmode"
}

wifi_updown() {
	#[ enable = "$1" ] && {
	#	wifi_updown disable "$2"
	#	scan_wifi
	#}
	if eval "type update-wifi" 2>/dev/null >/dev/null; then
		update-wifi
	fi

	[ -f /tmp/wlan_lock_file ] && exit 1
	/bin/touch /tmp/wlan_lock_file

	for driver in ${DRIVERS}; do (
		if eval "type pre_${driver}" 2>/dev/null >/dev/null; then
			eval "pre_${driver}" ${1}
		fi
	); done
	for device in ${2:-$DEVICES}; do (
		config_get disabled "$device" disabled
		[ 1 == "$disabled" ] && {
			echo "'$device' is disabled"
			set disable
		}
		config_get iftype "$device" type
		if eval "type ${1}_$iftype" 2>/dev/null >/dev/null; then
			eval "scan_$iftype '$device'"
			eval "${1}_$iftype '$device' dni" || echo "$device($iftype): ${1} failed"
		else
			echo "$device($iftype): Interface type not supported"
		fi
	); done
	for driver in ${DRIVERS}; do (
		if eval "type post_${driver}" 2>/dev/null >/dev/null; then
			eval "post_${driver}" ${1}
		fi
	); done
	if eval "type config_get_$CONFIGS" 2>/dev/null >/dev/null; then
		eval "config_get_$CONFIGS _tmp_radio_num radio_num"
		eval "config_get_$CONFIGS _tmp_security_type security_type"
		eval "config_get_$CONFIGS _tmp_radio_type radio_type"
		eval "config_get_$CONFIGS _tmp_led_blinking_setting led_blinking_setting"
	fi
	if [ "${1}" = "enable" ]; then
		for driver in ${DRIVERS}; do (
			if eval "on_led_${driver}" 2>/dev/null >/dev/null; then
				eval "on_led_${driver} $_tmp_radio_num $_tmp_security_type $_tmp_radio_type $_tmp_led_blinking_setting" || echo "$driver: on led failed"
			else
				echo "$driver: Interface type not supported"
			fi
		); done
	else
		for driver in ${DRIVERS}; do (
			if eval "force_off_led_${driver}" 2>/dev/null >/dev/null; then
				eval "force_off_led_${driver}" || echo "$driver: force off led failed"
			else
				echo "$driver: Interface type not supported"
			fi
		); done
	fi

	/bin/rm /tmp/wlan_lock_file
}

wifi_detect() {
	for driver in ${2:-$DRIVERS}; do (
		if eval "type detect_$driver" 2>/dev/null >/dev/null; then
			eval "detect_$driver dni $1" || echo "$driver: Detect failed" >&2
		else
			echo "$driver: Hardware detection not supported" >&2
		fi
	); done
}

start_net() {(
	local iface="$1"
	local config="$2"
	local vifmac="$3"

	[ -f "/var/run/$iface.pid" ] && kill "$(cat /var/run/${iface}.pid)" 2>/dev/null
	[ -z "$config" ] || {
		include /lib/network
		scan_interfaces
		for config in $config; do
			setup_interface "$iface" "$config" "" "$vifmac"
		done
	}
)}

set_wifi_up() {
	local cfg="$1"
	local ifname="$2"
	uci_set_state wireless "$cfg" up 1
	uci_set_state wireless "$cfg" ifname "$ifname"
}

set_wifi_down() {
	local cfg="$1"
	local vifs vif vifstr

	[ -f "/var/run/wifi-${cfg}.pid" ] &&
		kill "$(cat "/var/run/wifi-${cfg}.pid")" 2>/dev/null
	uci_revert_state wireless "$cfg"
	config_get vifs "$cfg" vifs
	for vif in $vifs; do
		uci_revert_state wireless "$vif"
	done
}

scan_wifi() {
	local cfgfile="$1"
	DEVICES=
	config_cb() {
		local type="$1"
		local section="$2"

		# section start
		case "$type" in
			wifi-device)
				append DEVICES "$section"
				config_set "$section" vifs ""
				config_set "$section" ht_capab ""
			;;
		esac

		# section end
		config_get TYPE "$CONFIG_SECTION" TYPE
		case "$TYPE" in
			wifi-iface)
				config_get device "$CONFIG_SECTION" device
				config_get vifs "$device" vifs 
				append vifs "$CONFIG_SECTION"
				config_set "$device" vifs "$vifs"
			;;
		esac
	}
	config_load "${cfgfile:-wireless}"
}

wifi_wps() {
	for device in ${DEVICES}; do (
		config_get iftype "$device" type
		if eval "type wps_$iftype" 2>/dev/null >/dev/null; then
			shift
			eval "wps_$iftype" "$device" "$@" || echo "$iftype: WPS failed" >&2
		else
			echo "$iftype: Hardware wps ion not supported" >&2
		fi
	); done
}

wifi_toggle() {
	local g_mode=
	local a_mode=

	if eval "type config_get_$CONFIGS" 2>/dev/null >/dev/null; then
		eval "config_get_$CONFIGS _tmp_state hw_btn_state"
	fi
	for device in ${DEVICES}; do
		config_get hwmode "$device" hwmode
		is11g=`echo $hwmode | grep -i g`
		is11a=`echo $hwmode | grep -i a`
		[ "x$is11g" != "x" ] && g_mode=1
		[ "x$is11a" != "x" ] && a_mode=1

		config_get iftype "$device" type
		(if eval "type wifitoggle_$iftype" 2>/dev/null >/dev/null; then
			shift
			eval "wifitoggle_$iftype" "$device" "$_tmp_state" "$@" || echo "$iftype: WIFITOGGLE failed" >&2
		else
			echo "$iftype: Hardware wifitoggle not supported" >&2
		fi);
	done
	if [ "$_tmp_state" = "on" ]; then
		next_state="off"
		[ "x$g_mode" != "x" ] && {
			if eval "type config_set_$CONFIGS" 2>/dev/null >/dev/null; then
				eval "config_set_$CONFIGS wl_onoff 11g 0"
			fi
		}
		[ "x$a_mode" != "x" ] && {
			if eval "type config_set_$CONFIGS" 2>/dev/null >/dev/null; then
				eval "config_set_$CONFIGS wl_onoff 11a 0"
			fi
		}
	else
		next_state="on"
		[ "x$g_mode" != "x" ] && {
			if eval "type config_set_$CONFIGS" 2>/dev/null >/dev/null; then
				eval "config_set_$CONFIGS wl_onoff 11g 1"
			fi
		}
		[ "x$a_mode" != "x" ] && {
			if eval "type config_set_$CONFIGS" 2>/dev/null >/dev/null; then
				eval "config_set_$CONFIGS wl_onoff 11a 1"
			fi
		}
	fi
	if eval "type config_set_$CONFIGS" 2>/dev/null >/dev/null; then
		eval "config_set_$CONFIGS hw_btn_state $next_state"
	fi
	if eval "type config_get_$CONFIGS" 2>/dev/null >/dev/null; then
		eval "config_get_$CONFIGS _tmp_radio_num radio_num"
		eval "config_get_$CONFIGS _tmp_security_type security_type"
		eval "config_get_$CONFIGS _tmp_radio_type radio_type"
		eval "config_get_$CONFIGS _tmp_led_blinking_setting led_blinking_setting"
	fi
	if [ "$next_state" = "on" ]; then
		for driver in ${DRIVERS}; do (
			if eval "on_led_${driver}" 2>/dev/null >/dev/null; then
				eval "on_led_${driver} $_tmp_radio_num $_tmp_security_type $_tmp_radio_type $_tmp_led_blinking_setting" || echo "$driver: on led failed"
			else
				echo "$driver: Interface type not supported"
			fi
		); done
	else
		for driver in ${DRIVERS}; do (
			if eval "force_off_led_${driver}" 2>/dev/null >/dev/null; then
				eval "force_off_led_${driver}" || echo "$driver: force off led failed"
			else
				echo "$driver: Interface type not supported"
			fi
		); done
	fi
	if eval "type config_commit_$CONFIGS" 2>/dev/null >/dev/null; then
		eval "config_commit_$CONFIGS"
	fi
}

wifi_schedule() {
	local band=$2
	local newstate=$3

	if eval "type config_get_$CONFIGS" 2>/dev/null >/dev/null; then
		eval "config_get_$CONFIGS _tmp_state hw_btn_state"
	fi
	for device in ${DEVICES}; do (
		config_get hwmode "$device" hwmode
		is11g=`echo $hwmode | grep -i g`
		is11a=`echo $hwmode | grep -i a`
		[ "$band" = "11g" -a "x$is11a" != "x" ] || [ "$band" = "11a" -a "x$is11g" != "x" ] && continue

		config_get iftype "$device" type
		if eval "type wifischedule_$iftype" 2>/dev/null >/dev/null; then
			shift
			eval "wifischedule_$iftype" "$device" "$_tmp_state" "$@" || echo "$iftype: WIFI SCHEDULE failed" >&2
		else
			echo "$iftype: Hardware wifi schedule not supported" >&2
		fi
	); done
	if [ "$newstate" = "on" -a "$_tmp_state" = "on" ]; then
		if eval "type config_set_$CONFIGS" 2>/dev/null >/dev/null; then
			eval "config_set_$CONFIGS sched_status $band 0"
		fi
		if eval "type config_set_$CONFIGS" 2>/dev/null >/dev/null; then
			eval "config_set_$CONFIGS wl_onoff $band 1"
		fi
	else
		if eval "type config_set_$CONFIGS" 2>/dev/null >/dev/null; then
			eval "config_set_$CONFIGS sched_status $band 1"
		fi
		if eval "type config_set_$CONFIGS" 2>/dev/null >/dev/null; then
			eval "config_set_$CONFIGS wl_onoff $band 0"
		fi
	fi
	if eval "type config_get_$CONFIGS" 2>/dev/null >/dev/null; then
		eval "config_get_$CONFIGS _tmp_radio_num radio_num"
		eval "config_get_$CONFIGS _tmp_security_type security_type"
		eval "config_get_$CONFIGS _tmp_radio_type radio_type"
		eval "config_get_$CONFIGS _tmp_led_blinking_setting led_blinking_setting"
	fi
	if [ "$newstate" = "on" -a "$_tmp_state" = "on" ]; then
		for driver in ${DRIVERS}; do (
			if eval "on_led_${driver}" 2>/dev/null >/dev/null; then
				eval "on_led_${driver} $_tmp_radio_num $_tmp_security_type $_tmp_radio_type $_tmp_led_blinking_setting" || echo "$driver: on led failed"
			else
				echo "$driver: Interface type not supported"
			fi
		); done
	else
		for driver in ${DRIVERS}; do (
			if eval "off_led_${driver}" 2>/dev/null >/dev/null; then
				eval "off_led_${driver} $_tmp_radio_num $_tmp_security_type $_tmp_radio_type $_tmp_led_blinking_setting" || echo "$driver: off led failed"
			else
				echo "$driver: Interface type not supported"
			fi
		); done
	fi
	if eval "type config_commit_$CONFIGS" 2>/dev/null >/dev/null; then
		eval "config_commit_$CONFIGS"
	fi
}

wifi_stainfo() {
	for device in ${DEVICES}; do (
		config_get iftype "$device" type
		if eval "type wifistainfo_$iftype" 2>/dev/null >/dev/null; then
			shift
			eval "wifistainfo_$iftype" "$device" "$@" || echo "$iftype: WIFI STAINFO failed" >&2
		else
			echo "$iftype: Hardware wifi stainfo not supported" >&2
		fi
	); done
}

wifi_radio() {
	local band=$2

	for device in ${DEVICES}; do (
		config_get hwmode "$device" hwmode
		is11g=`echo $hwmode | grep -i g`
		is11a=`echo $hwmode | grep -i a`
		[ "$band" = "11g" -a "x$is11a" != "x" ] || [ "$band" = "11a" -a "x$is11g" != "x" ] && continue

		config_get iftype "$device" type
		if eval "type wifiradio_$iftype" 2>/dev/null >/dev/null; then
			shift
			eval "wifiradio_$iftype" "$device" "$@" || echo "$iftype: WIFI RADIO failed" >&2
		else
			echo "$iftype: Hardware wifi radio not supported" >&2
		fi
	); done
}

wifi_statistic() {
	for device in ${DEVICES}; do (
		config_get iftype "$device" type
		if eval "type statistic_$iftype" 2>/dev/null >/dev/null; then
			eval "statistic_$iftype" "$device" || echo "$iftype: STATISTIC failed" >&2
		else
			echo "$iftype: Hardware statistic not supported" >&2
		fi
	); done
}

show_usage() {
    cat <<EOF
Usage: wlan <command> [<arguments>]

Commands:
    up                               : bring up wireless interfaces
    down                             : bring down wireless interfaces
    wps <arguments>                  : wps actions.
         --client_pin <pin number>   :: start WPS client PIN
         --pbc_start                 :: start WPS PBC
         --wps_stop                  :: stop WPS actions
    toggle                           : toggle wireless radio (ON <-> OFF)
    schedule <11g/11a> <on/off>      : do wireless schedule
    stainfo                          : show all attached wireless stations.
    radio <11g/11a> <arguments>      : actions related to radio
         --status                    :: show radio status (ON or OFF)
         --channel                   :: show current channel
         --coext <on/off>            :: enable/disable coexistence function.
    statistic                        :: show statistic info
    help                             : show this
EOF
}

DEVICES=
DRIVERS=
CONFIGS=
include /lib/wifi
scan_wifi

case "$1" in
	down) wifi_updown "disable" "$2";;
	detect) wifi_detect "$2";;
	wps) wifi_wps "$@";;
	toggle) wifi_toggle "$@";;
	schedule) wifi_schedule "$@";;
	stainfo) wifi_stainfo "$@";;
	radio) wifi_radio "$@";;
	up) wifi_updown "enable" "$2";;
	statistic ) wifi_statistic ;;
	*) show_usage ;;
esac

[ -f /tmp/wlan_lock_file ] && /bin/rm /tmp/wlan_lock_file