/** \file
 *  This C header file was generated by $ANTLR version 3.2 debian-7
 *
 *     -  From the grammar source file : SMARTPL.g
 *     -                            On : 2015-05-13 11:04:09
 *     -                 for the lexer : SMARTPLLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer SMARTPLLexer has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pSMARTPLLexer, which is returned from a call to SMARTPLLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 * * The methods in pSMARTPLLexer are  as follows:
 *
 *  -  void      pSMARTPLLexer->T__30(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->T__31(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->STRTAG(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->INTTAG(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->DATETAG(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->ENUMTAG(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->INCLUDES(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->IS(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->INTBOOL(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->GREATER(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->GREATEREQUAL(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->LESS(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->LESSEQUAL(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->EQUAL(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->AFTER(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->BEFORE(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->AGO(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->AND(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->OR(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->NOT(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->LPAR(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->RPAR(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->DATE(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->DATINTERVAL(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->ENUMVAL(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->STR(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->INT(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->WHITESPACE(pSMARTPLLexer)
 *  -  void      pSMARTPLLexer->Tokens(pSMARTPLLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_SMARTPLLexer_H
#define _SMARTPLLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct SMARTPLLexer_Ctx_struct SMARTPLLexer, * pSMARTPLLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for SMARTPLLexer
 */
struct SMARTPLLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;


     void (*mT__30)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mT__31)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mSTRTAG)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mINTTAG)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mDATETAG)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mENUMTAG)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mINCLUDES)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mIS)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mINTBOOL)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mGREATER)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mGREATEREQUAL)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mLESS)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mLESSEQUAL)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mEQUAL)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mAFTER)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mBEFORE)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mAGO)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mAND)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mOR)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mNOT)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mLPAR)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mRPAR)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mDATE)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mDATINTERVAL)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mENUMVAL)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mSTR)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mINT)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mWHITESPACE)	(struct SMARTPLLexer_Ctx_struct * ctx);
     void (*mTokens)	(struct SMARTPLLexer_Ctx_struct * ctx);    const char * (*getGrammarFileName)();
    void	    (*free)   (struct SMARTPLLexer_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pSMARTPLLexer SMARTPLLexerNew         (pANTLR3_INPUT_STREAM instream);
ANTLR3_API pSMARTPLLexer SMARTPLLexerNewSSD      (pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the lexer will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define INTBOOL      14
#define STRTAG      10
#define AGO      22
#define WHITESPACE      29
#define GREATEREQUAL      25
#define BEFORE      18
#define DATETAG      16
#define INT      15
#define NOT      7
#define AFTER      17
#define AND      6
#define EOF      -1
#define INCLUDES      11
#define STR      4
#define T__30      30
#define T__31      31
#define GREATER      24
#define LPAR      8
#define ENUMTAG      19
#define IS      12
#define ENUMVAL      20
#define EQUAL      28
#define OR      5
#define LESS      26
#define RPAR      9
#define DATE      21
#define LESSEQUAL      27
#define INTTAG      13
#define DATINTERVAL      23
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for SMARTPLLexer
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
