/** \file
 *  This C source file was generated by $ANTLR version 3.2 debian-7
 *
 *     -  From the grammar source file : SMARTPL.g
 *     -                            On : 2015-05-13 11:04:09
 *     -                 for the lexer : SMARTPLLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "SMARTPLLexer.h"
/* ----------------------------------------- */


/** String literals used by SMARTPLLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x61, 0x72, 0x74, 0x69, 0x73, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x61, 0x6C, 0x62, 0x75, 0x6D, 0x5F, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x61, 0x6C, 0x62, 0x75, 0x6D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x74, 0x69, 0x74, 0x6C, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x67, 0x65, 0x6E, 0x72, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x63, 0x6F, 0x6D, 0x70, 0x6F, 0x73, 0x65, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x70, 0x61, 0x74, 0x68,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x74, 0x79, 0x70, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x70, 0x6C, 0x61, 0x79, 0x5F, 0x63, 0x6F, 0x75, 0x6E, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x72, 0x61, 0x74, 0x69, 0x6E, 0x67,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x79, 0x65, 0x61, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x63, 0x6F, 0x6D, 0x70, 0x69, 0x6C, 0x61, 0x74, 0x69, 0x6F, 0x6E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_13[]  = { 0x74, 0x69, 0x6D, 0x65, 0x5F, 0x61, 0x64, 0x64, 0x65, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_14[]  = { 0x74, 0x69, 0x6D, 0x65, 0x5F, 0x70, 0x6C, 0x61, 0x79, 0x65, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_15[]  = { 0x64, 0x61, 0x74, 0x61, 0x5F, 0x6B, 0x69, 0x6E, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_16[]  = { 0x6D, 0x65, 0x64, 0x69, 0x61, 0x5F, 0x6B, 0x69, 0x6E, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_17[]  = { 0x69, 0x6E, 0x63, 0x6C, 0x75, 0x64, 0x65, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_18[]  = { 0x69, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_19[]  = { 0x3E, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_20[]  = { 0x3C, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_21[]  = { 0x61, 0x66, 0x74, 0x65, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_22[]  = { 0x62, 0x65, 0x66, 0x6F, 0x72, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_23[]  = { 0x61, 0x67, 0x6F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_24[]  = { 0x41, 0x4E, 0x44,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_25[]  = { 0x61, 0x6E, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_26[]  = { 0x4F, 0x52,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_27[]  = { 0x6F, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_28[]  = { 0x4E, 0x4F, 0x54,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_29[]  = { 0x6E, 0x6F, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_30[]  = { 0x74, 0x6F, 0x64, 0x61, 0x79,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_31[]  = { 0x79, 0x65, 0x73, 0x74, 0x65, 0x72, 0x64, 0x61, 0x79,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_32[]  = { 0x6C, 0x61, 0x73, 0x74, 0x20, 0x77, 0x65, 0x65, 0x6B,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_33[]  = { 0x6C, 0x61, 0x73, 0x74, 0x20, 0x6D, 0x6F, 0x6E, 0x74, 0x68,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_34[]  = { 0x6C, 0x61, 0x73, 0x74, 0x20, 0x79, 0x65, 0x61, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_35[]  = { 0x64, 0x61, 0x79, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_36[]  = { 0x77, 0x65, 0x65, 0x6B, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_37[]  = { 0x6D, 0x6F, 0x6E, 0x74, 0x68, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_38[]  = { 0x79, 0x65, 0x61, 0x72, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_39[]  = { 0x6D, 0x75, 0x73, 0x69, 0x63,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_40[]  = { 0x6D, 0x6F, 0x76, 0x69, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_41[]  = { 0x70, 0x6F, 0x64, 0x63, 0x61, 0x73, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_42[]  = { 0x61, 0x75, 0x64, 0x69, 0x6F, 0x62, 0x6F, 0x6F, 0x6B,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_43[]  = { 0x74, 0x76, 0x73, 0x68, 0x6F, 0x77,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_44[]  = { 0x66, 0x69, 0x6C, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_45[]  = { 0x75, 0x72, 0x6C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_46[]  = { 0x73, 0x70, 0x6F, 0x74, 0x69, 0x66, 0x79,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_47[]  = { 0x70, 0x69, 0x70, 0x65,  ANTLR3_STRING_TERMINATOR};




/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pSMARTPLLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pSMARTPLLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pSMARTPLLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pSMARTPLLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

 
/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER		    
#undef	    RULEMEMO		    
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or 16 bit input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_ASCII) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_ASCII

/* 8 bit "ASCII" (actually any 8 bit character set) */

#  define	    NEXTCHAR			((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP				((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR			((pANTLR3_UINT16)(INPUT->nextChar)) 
#  define	    DATAP				((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define	    CONSUME()											\
{																	\
    if	(NEXTCHAR < (DATAP + INPUT->sizeBuf))						\
    {																\
		INPUT->charPositionInLine++;								\
		if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)		\
		{															\
			INPUT->line++;											\
			INPUT->charPositionInLine	= 0;						\
			INPUT->currentLine		= (void *)(NEXTCHAR + 1);		\
		}															\
		INPUT->nextChar = (void *)(NEXTCHAR + 1);					\
    }																\
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()				INPUT->istream->consume(INPUT->istream)
#define	    LA(n)					INPUT->istream->_LA(INPUT->istream, n)

#endif
#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE  void	mT__30    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mT__31    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mSTRTAG    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mINTTAG    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mDATETAG    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mENUMTAG    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mINCLUDES    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mIS    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mINTBOOL    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mGREATER    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mGREATEREQUAL    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mLESS    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mLESSEQUAL    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mEQUAL    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mAFTER    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mBEFORE    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mAGO    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mAND    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mOR    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mNOT    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mLPAR    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mRPAR    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mDATE    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mDATINTERVAL    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mENUMVAL    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mSTR    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mINT    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mWHITESPACE    (pSMARTPLLexer ctx);
static ANTLR3_INLINE  void	mTokens    (pSMARTPLLexer ctx);
static void	SMARTPLLexerFree(pSMARTPLLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
SMARTPLLexerFree  (pSMARTPLLexer ctx)
{
    LEXER->free(LEXER);
    
    ANTLR3_FREE(ctx);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "SMARTPL.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called SMARTPLLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return 
 *     - Success pSMARTPLLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pSMARTPLLexer SMARTPLLexerNew         
(pANTLR3_INPUT_STREAM instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return SMARTPLLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called SMARTPLLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return 
 *     - Success pSMARTPLLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pSMARTPLLexer SMARTPLLexerNewSSD         
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pSMARTPLLexer ctx; // Context structure we will build and return

    ctx = (pSMARTPLLexer) ANTLR3_CALLOC(1, sizeof(SMARTPLLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in SMARTPLLexer.h here so you can get a sense
     * of what goes where.
     */
    
    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);
    
    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our SMARTPLLexer interface
     */
    ctx->mT__30	= mT__30;
    ctx->mT__31	= mT__31;
    ctx->mSTRTAG	= mSTRTAG;
    ctx->mINTTAG	= mINTTAG;
    ctx->mDATETAG	= mDATETAG;
    ctx->mENUMTAG	= mENUMTAG;
    ctx->mINCLUDES	= mINCLUDES;
    ctx->mIS	= mIS;
    ctx->mINTBOOL	= mINTBOOL;
    ctx->mGREATER	= mGREATER;
    ctx->mGREATEREQUAL	= mGREATEREQUAL;
    ctx->mLESS	= mLESS;
    ctx->mLESSEQUAL	= mLESSEQUAL;
    ctx->mEQUAL	= mEQUAL;
    ctx->mAFTER	= mAFTER;
    ctx->mBEFORE	= mBEFORE;
    ctx->mAGO	= mAGO;
    ctx->mAND	= mAND;
    ctx->mOR	= mOR;
    ctx->mNOT	= mNOT;
    ctx->mLPAR	= mLPAR;
    ctx->mRPAR	= mRPAR;
    ctx->mDATE	= mDATE;
    ctx->mDATINTERVAL	= mDATINTERVAL;
    ctx->mENUMVAL	= mENUMVAL;
    ctx->mSTR	= mSTR;
    ctx->mINT	= mINT;
    ctx->mWHITESPACE	= mWHITESPACE;
    ctx->mTokens	= mTokens;
    
    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;
    
    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);
    
    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= SMARTPLLexerFree;

    
    


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
 

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__30
 *
 * Looks to match the characters the constitute the token T__30
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__30(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__30;
       
    
    // SMARTPL.g:7:7: ( '{' )
    // SMARTPL.g:7:9: '{'
    {
        MATCHC('{'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__30Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__30Ex; /* Prevent compiler warnings */
    ruleT__30Ex: ;

}
// $ANTLR end T__30

//   Comes from: 8:7: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__31
 *
 * Looks to match the characters the constitute the token T__31
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__31(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__31;
       
    
    // SMARTPL.g:8:7: ( '}' )
    // SMARTPL.g:8:9: '}'
    {
        MATCHC('}'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__31Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__31Ex; /* Prevent compiler warnings */
    ruleT__31Ex: ;

}
// $ANTLR end T__31

//   Comes from: 56:9: ( 'artist' | 'album_artist' | 'album' | 'title' | 'genre' | 'composer' | 'path' | 'type' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRTAG
 *
 * Looks to match the characters the constitute the token STRTAG
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRTAG(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = STRTAG;
       
    
    {
        //  SMARTPL.g:56:9: ( 'artist' | 'album_artist' | 'album' | 'title' | 'genre' | 'composer' | 'path' | 'type' )
        
        ANTLR3_UINT32 alt1;

        alt1=8;

        switch ( LA(1) ) 
        {
        case 'a':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'r':
        			{
        				alt1=1;
        			}
        		    break;
        		case 'l':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'b':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'u':
        							{
        								switch ( LA(5) ) 
        								{
        								case 'm':
        									{
        										switch ( LA(6) ) 
        										{
        										case '_':
        											{
        												alt1=2;
        											}
        										    break;

        										default:
        										    alt1=3;}

        									}
        								    break;

        								default:
        								    CONSTRUCTEX();
        								    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        								    EXCEPTION->message      = (void *)"";
        								    EXCEPTION->decisionNum  = 1;
        								    EXCEPTION->state        = 11;


        								    goto ruleSTRTAGEx;
        								}

        							}
        						    break;

        						default:
        						    CONSTRUCTEX();
        						    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        						    EXCEPTION->message      = (void *)"";
        						    EXCEPTION->decisionNum  = 1;
        						    EXCEPTION->state        = 10;


        						    goto ruleSTRTAGEx;
        						}

        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 1;
        				    EXCEPTION->state        = 7;


        				    goto ruleSTRTAGEx;
        				}

        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 1;
        		    EXCEPTION->state        = 1;


        		    goto ruleSTRTAGEx;
        		}

        	}
            break;
        case 't':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'i':
        			{
        				alt1=4;
        			}
        		    break;
        		case 'y':
        			{
        				alt1=8;
        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 1;
        		    EXCEPTION->state        = 2;


        		    goto ruleSTRTAGEx;
        		}

        	}
            break;
        case 'g':
        	{
        		alt1=5;
        	}
            break;
        case 'c':
        	{
        		alt1=6;
        	}
            break;
        case 'p':
        	{
        		alt1=7;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 1;
            EXCEPTION->state        = 0;


            goto ruleSTRTAGEx;
        }

        switch (alt1) 
        {
    	case 1:
    	    // SMARTPL.g:56:11: 'artist'
    	    {
    	        MATCHS(lit_1); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleSTRTAGEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // SMARTPL.g:57:6: 'album_artist'
    	    {
    	        MATCHS(lit_2); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleSTRTAGEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // SMARTPL.g:58:6: 'album'
    	    {
    	        MATCHS(lit_3); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleSTRTAGEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // SMARTPL.g:59:6: 'title'
    	    {
    	        MATCHS(lit_4); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleSTRTAGEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // SMARTPL.g:60:6: 'genre'
    	    {
    	        MATCHS(lit_5); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleSTRTAGEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // SMARTPL.g:61:6: 'composer'
    	    {
    	        MATCHS(lit_6); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleSTRTAGEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // SMARTPL.g:62:6: 'path'
    	    {
    	        MATCHS(lit_7); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleSTRTAGEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // SMARTPL.g:63:6: 'type'
    	    {
    	        MATCHS(lit_8); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleSTRTAGEx;
    	        }



    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSTRTAGEx; /* Prevent compiler warnings */
    ruleSTRTAGEx: ;

}
// $ANTLR end STRTAG

//   Comes from: 66:9: ( 'play_count' | 'rating' | 'year' | 'compilation' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INTTAG
 *
 * Looks to match the characters the constitute the token INTTAG
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINTTAG(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INTTAG;
       
    
    {
        //  SMARTPL.g:66:9: ( 'play_count' | 'rating' | 'year' | 'compilation' )
        
        ANTLR3_UINT32 alt2;

        alt2=4;

        switch ( LA(1) ) 
        {
        case 'p':
        	{
        		alt2=1;
        	}
            break;
        case 'r':
        	{
        		alt2=2;
        	}
            break;
        case 'y':
        	{
        		alt2=3;
        	}
            break;
        case 'c':
        	{
        		alt2=4;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 2;
            EXCEPTION->state        = 0;


            goto ruleINTTAGEx;
        }

        switch (alt2) 
        {
    	case 1:
    	    // SMARTPL.g:66:11: 'play_count'
    	    {
    	        MATCHS(lit_9); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleINTTAGEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // SMARTPL.g:67:6: 'rating'
    	    {
    	        MATCHS(lit_10); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleINTTAGEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // SMARTPL.g:68:6: 'year'
    	    {
    	        MATCHS(lit_11); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleINTTAGEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // SMARTPL.g:69:6: 'compilation'
    	    {
    	        MATCHS(lit_12); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleINTTAGEx;
    	        }



    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleINTTAGEx; /* Prevent compiler warnings */
    ruleINTTAGEx: ;

}
// $ANTLR end INTTAG

//   Comes from: 72:10: ( 'time_added' | 'time_played' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DATETAG
 *
 * Looks to match the characters the constitute the token DATETAG
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDATETAG(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DATETAG;
       
    
    {
        //  SMARTPL.g:72:10: ( 'time_added' | 'time_played' )
        
        ANTLR3_UINT32 alt3;

        alt3=2;

        switch ( LA(1) ) 
        {
        case 't':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'i':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'm':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'e':
        							{
        								switch ( LA(5) ) 
        								{
        								case '_':
        									{
        										switch ( LA(6) ) 
        										{
        										case 'a':
        											{
        												alt3=1;
        											}
        										    break;
        										case 'p':
        											{
        												alt3=2;
        											}
        										    break;

        										default:
        										    CONSTRUCTEX();
        										    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        										    EXCEPTION->message      = (void *)"";
        										    EXCEPTION->decisionNum  = 3;
        										    EXCEPTION->state        = 5;


        										    goto ruleDATETAGEx;
        										}

        									}
        								    break;

        								default:
        								    CONSTRUCTEX();
        								    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        								    EXCEPTION->message      = (void *)"";
        								    EXCEPTION->decisionNum  = 3;
        								    EXCEPTION->state        = 4;


        								    goto ruleDATETAGEx;
        								}

        							}
        						    break;

        						default:
        						    CONSTRUCTEX();
        						    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        						    EXCEPTION->message      = (void *)"";
        						    EXCEPTION->decisionNum  = 3;
        						    EXCEPTION->state        = 3;


        						    goto ruleDATETAGEx;
        						}

        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 3;
        				    EXCEPTION->state        = 2;


        				    goto ruleDATETAGEx;
        				}

        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 3;
        		    EXCEPTION->state        = 1;


        		    goto ruleDATETAGEx;
        		}

        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 3;
            EXCEPTION->state        = 0;


            goto ruleDATETAGEx;
        }

        switch (alt3) 
        {
    	case 1:
    	    // SMARTPL.g:72:12: 'time_added'
    	    {
    	        MATCHS(lit_13); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleDATETAGEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // SMARTPL.g:73:6: 'time_played'
    	    {
    	        MATCHS(lit_14); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleDATETAGEx;
    	        }



    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleDATETAGEx; /* Prevent compiler warnings */
    ruleDATETAGEx: ;

}
// $ANTLR end DATETAG

//   Comes from: 76:10: ( 'data_kind' | 'media_kind' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ENUMTAG
 *
 * Looks to match the characters the constitute the token ENUMTAG
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mENUMTAG(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ENUMTAG;
       
    
    {
        //  SMARTPL.g:76:10: ( 'data_kind' | 'media_kind' )
        
        ANTLR3_UINT32 alt4;

        alt4=2;

        switch ( LA(1) ) 
        {
        case 'd':
        	{
        		alt4=1;
        	}
            break;
        case 'm':
        	{
        		alt4=2;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 4;
            EXCEPTION->state        = 0;


            goto ruleENUMTAGEx;
        }

        switch (alt4) 
        {
    	case 1:
    	    // SMARTPL.g:76:12: 'data_kind'
    	    {
    	        MATCHS(lit_15); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleENUMTAGEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // SMARTPL.g:77:6: 'media_kind'
    	    {
    	        MATCHS(lit_16); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleENUMTAGEx;
    	        }



    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleENUMTAGEx; /* Prevent compiler warnings */
    ruleENUMTAGEx: ;

}
// $ANTLR end ENUMTAG

//   Comes from: 80:10: ( 'includes' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INCLUDES
 *
 * Looks to match the characters the constitute the token INCLUDES
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINCLUDES(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INCLUDES;
       
    
    // SMARTPL.g:80:10: ( 'includes' )
    // SMARTPL.g:80:12: 'includes'
    {
        MATCHS(lit_17); 
        if  (HASEXCEPTION())
        {
            goto ruleINCLUDESEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleINCLUDESEx; /* Prevent compiler warnings */
    ruleINCLUDESEx: ;

}
// $ANTLR end INCLUDES

//   Comes from: 83:6: ( 'is' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start IS
 *
 * Looks to match the characters the constitute the token IS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mIS(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = IS;
       
    
    // SMARTPL.g:83:6: ( 'is' )
    // SMARTPL.g:83:8: 'is'
    {
        MATCHS(lit_18); 
        if  (HASEXCEPTION())
        {
            goto ruleISEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleISEx; /* Prevent compiler warnings */
    ruleISEx: ;

}
// $ANTLR end IS

//   Comes from: 86:10: ( ( GREATER | GREATEREQUAL | LESS | LESSEQUAL | EQUAL ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INTBOOL
 *
 * Looks to match the characters the constitute the token INTBOOL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINTBOOL(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INTBOOL;
       
    
    // SMARTPL.g:86:10: ( ( GREATER | GREATEREQUAL | LESS | LESSEQUAL | EQUAL ) )
    // SMARTPL.g:86:12: ( GREATER | GREATEREQUAL | LESS | LESSEQUAL | EQUAL )
    {

        // SMARTPL.g:86:12: ( GREATER | GREATEREQUAL | LESS | LESSEQUAL | EQUAL )
        {
            int alt5=5;
            switch ( LA(1) ) 
            {
            case '>':
            	{
            		switch ( LA(2) ) 
            		{
            		case '=':
            			{
            				alt5=2;
            			}
            		    break;

            		default:
            		    alt5=1;}

            	}
                break;
            case '<':
            	{
            		switch ( LA(2) ) 
            		{
            		case '=':
            			{
            				alt5=4;
            			}
            		    break;

            		default:
            		    alt5=3;}

            	}
                break;
            case '=':
            	{
            		alt5=5;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 5;
                EXCEPTION->state        = 0;


                goto ruleINTBOOLEx;
            }

            switch (alt5) 
            {
        	case 1:
        	    // SMARTPL.g:86:13: GREATER
        	    {
        	        /* 86:13: GREATER */
        	        mGREATER(ctx ); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleINTBOOLEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // SMARTPL.g:86:21: GREATEREQUAL
        	    {
        	        /* 86:21: GREATEREQUAL */
        	        mGREATEREQUAL(ctx ); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleINTBOOLEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // SMARTPL.g:86:34: LESS
        	    {
        	        /* 86:34: LESS */
        	        mLESS(ctx ); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleINTBOOLEx;
        	        }


        	    }
        	    break;
        	case 4:
        	    // SMARTPL.g:86:39: LESSEQUAL
        	    {
        	        /* 86:39: LESSEQUAL */
        	        mLESSEQUAL(ctx ); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleINTBOOLEx;
        	        }


        	    }
        	    break;
        	case 5:
        	    // SMARTPL.g:86:49: EQUAL
        	    {
        	        /* 86:49: EQUAL */
        	        mEQUAL(ctx ); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleINTBOOLEx;
        	        }


        	    }
        	    break;

            }
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleINTBOOLEx; /* Prevent compiler warnings */
    ruleINTBOOLEx: ;

}
// $ANTLR end INTBOOL

//   Comes from: 90:10: ( '>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start GREATER
 *
 * Looks to match the characters the constitute the token GREATER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mGREATER(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // SMARTPL.g:90:10: ( '>' )
    // SMARTPL.g:90:12: '>'
    {
        MATCHC('>'); 
        if  (HASEXCEPTION())
        {
            goto ruleGREATEREx;
        }


    }



    // This is where rules clean up and exit
    //
    goto ruleGREATEREx; /* Prevent compiler warnings */
    ruleGREATEREx: ;

}
// $ANTLR end GREATER

//   Comes from: 94:13: ( '>=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start GREATEREQUAL
 *
 * Looks to match the characters the constitute the token GREATEREQUAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mGREATEREQUAL(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // SMARTPL.g:94:13: ( '>=' )
    // SMARTPL.g:94:15: '>='
    {
        MATCHS(lit_19); 
        if  (HASEXCEPTION())
        {
            goto ruleGREATEREQUALEx;
        }



    }



    // This is where rules clean up and exit
    //
    goto ruleGREATEREQUALEx; /* Prevent compiler warnings */
    ruleGREATEREQUALEx: ;

}
// $ANTLR end GREATEREQUAL

//   Comes from: 98:7: ( '<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LESS
 *
 * Looks to match the characters the constitute the token LESS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLESS(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // SMARTPL.g:98:7: ( '<' )
    // SMARTPL.g:98:9: '<'
    {
        MATCHC('<'); 
        if  (HASEXCEPTION())
        {
            goto ruleLESSEx;
        }


    }



    // This is where rules clean up and exit
    //
    goto ruleLESSEx; /* Prevent compiler warnings */
    ruleLESSEx: ;

}
// $ANTLR end LESS

//   Comes from: 102:11: ( '<=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LESSEQUAL
 *
 * Looks to match the characters the constitute the token LESSEQUAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLESSEQUAL(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // SMARTPL.g:102:11: ( '<=' )
    // SMARTPL.g:102:13: '<='
    {
        MATCHS(lit_20); 
        if  (HASEXCEPTION())
        {
            goto ruleLESSEQUALEx;
        }



    }



    // This is where rules clean up and exit
    //
    goto ruleLESSEQUALEx; /* Prevent compiler warnings */
    ruleLESSEQUALEx: ;

}
// $ANTLR end LESSEQUAL

//   Comes from: 106:8: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EQUAL
 *
 * Looks to match the characters the constitute the token EQUAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEQUAL(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // SMARTPL.g:106:8: ( '=' )
    // SMARTPL.g:106:10: '='
    {
        MATCHC('='); 
        if  (HASEXCEPTION())
        {
            goto ruleEQUALEx;
        }


    }



    // This is where rules clean up and exit
    //
    goto ruleEQUALEx; /* Prevent compiler warnings */
    ruleEQUALEx: ;

}
// $ANTLR end EQUAL

//   Comes from: 109:8: ( 'after' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start AFTER
 *
 * Looks to match the characters the constitute the token AFTER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mAFTER(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = AFTER;
       
    
    // SMARTPL.g:109:8: ( 'after' )
    // SMARTPL.g:109:10: 'after'
    {
        MATCHS(lit_21); 
        if  (HASEXCEPTION())
        {
            goto ruleAFTEREx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleAFTEREx; /* Prevent compiler warnings */
    ruleAFTEREx: ;

}
// $ANTLR end AFTER

//   Comes from: 112:9: ( 'before' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BEFORE
 *
 * Looks to match the characters the constitute the token BEFORE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBEFORE(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BEFORE;
       
    
    // SMARTPL.g:112:9: ( 'before' )
    // SMARTPL.g:112:11: 'before'
    {
        MATCHS(lit_22); 
        if  (HASEXCEPTION())
        {
            goto ruleBEFOREEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleBEFOREEx; /* Prevent compiler warnings */
    ruleBEFOREEx: ;

}
// $ANTLR end BEFORE

//   Comes from: 115:7: ( 'ago' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start AGO
 *
 * Looks to match the characters the constitute the token AGO
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mAGO(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = AGO;
       
    
    // SMARTPL.g:115:7: ( 'ago' )
    // SMARTPL.g:115:9: 'ago'
    {
        MATCHS(lit_23); 
        if  (HASEXCEPTION())
        {
            goto ruleAGOEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleAGOEx; /* Prevent compiler warnings */
    ruleAGOEx: ;

}
// $ANTLR end AGO

//   Comes from: 118:7: ( 'AND' | 'and' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start AND
 *
 * Looks to match the characters the constitute the token AND
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mAND(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = AND;
       
    
    {
        //  SMARTPL.g:118:7: ( 'AND' | 'and' )
        
        ANTLR3_UINT32 alt6;

        alt6=2;

        switch ( LA(1) ) 
        {
        case 'A':
        	{
        		alt6=1;
        	}
            break;
        case 'a':
        	{
        		alt6=2;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 6;
            EXCEPTION->state        = 0;


            goto ruleANDEx;
        }

        switch (alt6) 
        {
    	case 1:
    	    // SMARTPL.g:118:9: 'AND'
    	    {
    	        MATCHS(lit_24); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleANDEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // SMARTPL.g:119:6: 'and'
    	    {
    	        MATCHS(lit_25); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleANDEx;
    	        }



    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleANDEx; /* Prevent compiler warnings */
    ruleANDEx: ;

}
// $ANTLR end AND

//   Comes from: 122:6: ( 'OR' | 'or' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OR
 *
 * Looks to match the characters the constitute the token OR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOR(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OR;
       
    
    {
        //  SMARTPL.g:122:6: ( 'OR' | 'or' )
        
        ANTLR3_UINT32 alt7;

        alt7=2;

        switch ( LA(1) ) 
        {
        case 'O':
        	{
        		alt7=1;
        	}
            break;
        case 'o':
        	{
        		alt7=2;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 7;
            EXCEPTION->state        = 0;


            goto ruleOREx;
        }

        switch (alt7) 
        {
    	case 1:
    	    // SMARTPL.g:122:8: 'OR'
    	    {
    	        MATCHS(lit_26); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleOREx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // SMARTPL.g:123:6: 'or'
    	    {
    	        MATCHS(lit_27); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleOREx;
    	        }



    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleOREx; /* Prevent compiler warnings */
    ruleOREx: ;

}
// $ANTLR end OR

//   Comes from: 126:7: ( 'NOT' | 'not' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NOT
 *
 * Looks to match the characters the constitute the token NOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNOT(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NOT;
       
    
    {
        //  SMARTPL.g:126:7: ( 'NOT' | 'not' )
        
        ANTLR3_UINT32 alt8;

        alt8=2;

        switch ( LA(1) ) 
        {
        case 'N':
        	{
        		alt8=1;
        	}
            break;
        case 'n':
        	{
        		alt8=2;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 8;
            EXCEPTION->state        = 0;


            goto ruleNOTEx;
        }

        switch (alt8) 
        {
    	case 1:
    	    // SMARTPL.g:126:9: 'NOT'
    	    {
    	        MATCHS(lit_28); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleNOTEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // SMARTPL.g:127:6: 'not'
    	    {
    	        MATCHS(lit_29); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleNOTEx;
    	        }



    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleNOTEx; /* Prevent compiler warnings */
    ruleNOTEx: ;

}
// $ANTLR end NOT

//   Comes from: 130:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LPAR
 *
 * Looks to match the characters the constitute the token LPAR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLPAR(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LPAR;
       
    
    // SMARTPL.g:130:7: ( '(' )
    // SMARTPL.g:130:9: '('
    {
        MATCHC('('); 
        if  (HASEXCEPTION())
        {
            goto ruleLPAREx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleLPAREx; /* Prevent compiler warnings */
    ruleLPAREx: ;

}
// $ANTLR end LPAR

//   Comes from: 133:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RPAR
 *
 * Looks to match the characters the constitute the token RPAR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRPAR(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RPAR;
       
    
    // SMARTPL.g:133:7: ( ')' )
    // SMARTPL.g:133:9: ')'
    {
        MATCHC(')'); 
        if  (HASEXCEPTION())
        {
            goto ruleRPAREx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleRPAREx; /* Prevent compiler warnings */
    ruleRPAREx: ;

}
// $ANTLR end RPAR

//   Comes from: 136:7: ( ( '0' .. '9' ) ( '0' .. '9' ) ( '0' .. '9' ) ( '0' .. '9' ) '-' ( '0' .. '1' ) ( '0' .. '9' ) '-' ( '0' .. '3' ) ( '0' .. '9' ) | 'today' | 'yesterday' | 'last week' | 'last month' | 'last year' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DATE
 *
 * Looks to match the characters the constitute the token DATE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDATE(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DATE;
       
    
    {
        //  SMARTPL.g:136:7: ( ( '0' .. '9' ) ( '0' .. '9' ) ( '0' .. '9' ) ( '0' .. '9' ) '-' ( '0' .. '1' ) ( '0' .. '9' ) '-' ( '0' .. '3' ) ( '0' .. '9' ) | 'today' | 'yesterday' | 'last week' | 'last month' | 'last year' )
        
        ANTLR3_UINT32 alt9;

        alt9=6;

        switch ( LA(1) ) 
        {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt9=1;
        	}
            break;
        case 't':
        	{
        		alt9=2;
        	}
            break;
        case 'y':
        	{
        		alt9=3;
        	}
            break;
        case 'l':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'a':
        			{
        				switch ( LA(3) ) 
        				{
        				case 's':
        					{
        						switch ( LA(4) ) 
        						{
        						case 't':
        							{
        								switch ( LA(5) ) 
        								{
        								case ' ':
        									{
        										switch ( LA(6) ) 
        										{
        										case 'w':
        											{
        												alt9=4;
        											}
        										    break;
        										case 'm':
        											{
        												alt9=5;
        											}
        										    break;
        										case 'y':
        											{
        												alt9=6;
        											}
        										    break;

        										default:
        										    CONSTRUCTEX();
        										    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        										    EXCEPTION->message      = (void *)"";
        										    EXCEPTION->decisionNum  = 9;
        										    EXCEPTION->state        = 8;


        										    goto ruleDATEEx;
        										}

        									}
        								    break;

        								default:
        								    CONSTRUCTEX();
        								    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        								    EXCEPTION->message      = (void *)"";
        								    EXCEPTION->decisionNum  = 9;
        								    EXCEPTION->state        = 7;


        								    goto ruleDATEEx;
        								}

        							}
        						    break;

        						default:
        						    CONSTRUCTEX();
        						    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        						    EXCEPTION->message      = (void *)"";
        						    EXCEPTION->decisionNum  = 9;
        						    EXCEPTION->state        = 6;


        						    goto ruleDATEEx;
        						}

        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 9;
        				    EXCEPTION->state        = 5;


        				    goto ruleDATEEx;
        				}

        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 9;
        		    EXCEPTION->state        = 4;


        		    goto ruleDATEEx;
        		}

        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 9;
            EXCEPTION->state        = 0;


            goto ruleDATEEx;
        }

        switch (alt9) 
        {
    	case 1:
    	    // SMARTPL.g:136:9: ( '0' .. '9' ) ( '0' .. '9' ) ( '0' .. '9' ) ( '0' .. '9' ) '-' ( '0' .. '1' ) ( '0' .. '9' ) '-' ( '0' .. '3' ) ( '0' .. '9' )
    	    {
    	        // SMARTPL.g:136:9: ( '0' .. '9' )
    	        // SMARTPL.g:136:10: '0' .. '9'
    	        {
    	            MATCHRANGE('0', '9'); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleDATEEx;
    	            }


    	        }

    	        // SMARTPL.g:136:19: ( '0' .. '9' )
    	        // SMARTPL.g:136:20: '0' .. '9'
    	        {
    	            MATCHRANGE('0', '9'); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleDATEEx;
    	            }


    	        }

    	        // SMARTPL.g:136:29: ( '0' .. '9' )
    	        // SMARTPL.g:136:30: '0' .. '9'
    	        {
    	            MATCHRANGE('0', '9'); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleDATEEx;
    	            }


    	        }

    	        // SMARTPL.g:136:39: ( '0' .. '9' )
    	        // SMARTPL.g:136:40: '0' .. '9'
    	        {
    	            MATCHRANGE('0', '9'); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleDATEEx;
    	            }


    	        }

    	        MATCHC('-'); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleDATEEx;
    	        }

    	        // SMARTPL.g:136:52: ( '0' .. '1' )
    	        // SMARTPL.g:136:53: '0' .. '1'
    	        {
    	            MATCHRANGE('0', '1'); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleDATEEx;
    	            }


    	        }

    	        // SMARTPL.g:136:62: ( '0' .. '9' )
    	        // SMARTPL.g:136:63: '0' .. '9'
    	        {
    	            MATCHRANGE('0', '9'); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleDATEEx;
    	            }


    	        }

    	        MATCHC('-'); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleDATEEx;
    	        }

    	        // SMARTPL.g:136:75: ( '0' .. '3' )
    	        // SMARTPL.g:136:76: '0' .. '3'
    	        {
    	            MATCHRANGE('0', '3'); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleDATEEx;
    	            }


    	        }

    	        // SMARTPL.g:136:85: ( '0' .. '9' )
    	        // SMARTPL.g:136:86: '0' .. '9'
    	        {
    	            MATCHRANGE('0', '9'); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleDATEEx;
    	            }


    	        }


    	    }
    	    break;
    	case 2:
    	    // SMARTPL.g:137:6: 'today'
    	    {
    	        MATCHS(lit_30); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleDATEEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // SMARTPL.g:138:6: 'yesterday'
    	    {
    	        MATCHS(lit_31); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleDATEEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // SMARTPL.g:139:6: 'last week'
    	    {
    	        MATCHS(lit_32); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleDATEEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // SMARTPL.g:140:6: 'last month'
    	    {
    	        MATCHS(lit_33); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleDATEEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // SMARTPL.g:141:6: 'last year'
    	    {
    	        MATCHS(lit_34); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleDATEEx;
    	        }



    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleDATEEx; /* Prevent compiler warnings */
    ruleDATEEx: ;

}
// $ANTLR end DATE

//   Comes from: 144:13: ( 'days' | 'weeks' | 'months' | 'years' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DATINTERVAL
 *
 * Looks to match the characters the constitute the token DATINTERVAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDATINTERVAL(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DATINTERVAL;
       
    
    {
        //  SMARTPL.g:144:13: ( 'days' | 'weeks' | 'months' | 'years' )
        
        ANTLR3_UINT32 alt10;

        alt10=4;

        switch ( LA(1) ) 
        {
        case 'd':
        	{
        		alt10=1;
        	}
            break;
        case 'w':
        	{
        		alt10=2;
        	}
            break;
        case 'm':
        	{
        		alt10=3;
        	}
            break;
        case 'y':
        	{
        		alt10=4;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 10;
            EXCEPTION->state        = 0;


            goto ruleDATINTERVALEx;
        }

        switch (alt10) 
        {
    	case 1:
    	    // SMARTPL.g:144:15: 'days'
    	    {
    	        MATCHS(lit_35); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleDATINTERVALEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // SMARTPL.g:145:6: 'weeks'
    	    {
    	        MATCHS(lit_36); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleDATINTERVALEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // SMARTPL.g:146:6: 'months'
    	    {
    	        MATCHS(lit_37); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleDATINTERVALEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // SMARTPL.g:147:6: 'years'
    	    {
    	        MATCHS(lit_38); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleDATINTERVALEx;
    	        }



    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleDATINTERVALEx; /* Prevent compiler warnings */
    ruleDATINTERVALEx: ;

}
// $ANTLR end DATINTERVAL

//   Comes from: 150:10: ( 'music' | 'movie' | 'podcast' | 'audiobook' | 'tvshow' | 'file' | 'url' | 'spotify' | 'pipe' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ENUMVAL
 *
 * Looks to match the characters the constitute the token ENUMVAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mENUMVAL(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ENUMVAL;
       
    
    {
        //  SMARTPL.g:150:10: ( 'music' | 'movie' | 'podcast' | 'audiobook' | 'tvshow' | 'file' | 'url' | 'spotify' | 'pipe' )
        
        ANTLR3_UINT32 alt11;

        alt11=9;

        switch ( LA(1) ) 
        {
        case 'm':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'u':
        			{
        				alt11=1;
        			}
        		    break;
        		case 'o':
        			{
        				alt11=2;
        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 11;
        		    EXCEPTION->state        = 1;


        		    goto ruleENUMVALEx;
        		}

        	}
            break;
        case 'p':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'o':
        			{
        				alt11=3;
        			}
        		    break;
        		case 'i':
        			{
        				alt11=9;
        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 11;
        		    EXCEPTION->state        = 2;


        		    goto ruleENUMVALEx;
        		}

        	}
            break;
        case 'a':
        	{
        		alt11=4;
        	}
            break;
        case 't':
        	{
        		alt11=5;
        	}
            break;
        case 'f':
        	{
        		alt11=6;
        	}
            break;
        case 'u':
        	{
        		alt11=7;
        	}
            break;
        case 's':
        	{
        		alt11=8;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 11;
            EXCEPTION->state        = 0;


            goto ruleENUMVALEx;
        }

        switch (alt11) 
        {
    	case 1:
    	    // SMARTPL.g:150:12: 'music'
    	    {
    	        MATCHS(lit_39); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleENUMVALEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // SMARTPL.g:151:6: 'movie'
    	    {
    	        MATCHS(lit_40); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleENUMVALEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // SMARTPL.g:152:6: 'podcast'
    	    {
    	        MATCHS(lit_41); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleENUMVALEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // SMARTPL.g:153:6: 'audiobook'
    	    {
    	        MATCHS(lit_42); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleENUMVALEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // SMARTPL.g:154:6: 'tvshow'
    	    {
    	        MATCHS(lit_43); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleENUMVALEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // SMARTPL.g:155:6: 'file'
    	    {
    	        MATCHS(lit_44); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleENUMVALEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // SMARTPL.g:156:6: 'url'
    	    {
    	        MATCHS(lit_45); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleENUMVALEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // SMARTPL.g:157:6: 'spotify'
    	    {
    	        MATCHS(lit_46); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleENUMVALEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // SMARTPL.g:158:6: 'pipe'
    	    {
    	        MATCHS(lit_47); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleENUMVALEx;
    	        }



    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleENUMVALEx; /* Prevent compiler warnings */
    ruleENUMVALEx: ;

}
// $ANTLR end ENUMVAL

//   Comes from: 161:7: ( '\"' (~ ( '\"' ) )+ '\"' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STR
 *
 * Looks to match the characters the constitute the token STR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTR(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = STR;
       
    
    // SMARTPL.g:161:7: ( '\"' (~ ( '\"' ) )+ '\"' )
    // SMARTPL.g:161:9: '\"' (~ ( '\"' ) )+ '\"'
    {
        MATCHC('"'); 
        if  (HASEXCEPTION())
        {
            goto ruleSTREx;
        }

        // SMARTPL.g:161:13: (~ ( '\"' ) )+
        {
            int cnt12=0;

            for (;;)
            {
                int alt12=2;
        	{
        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	    */
        	    int LA12_0 = LA(1);
        	    if ( (((LA12_0 >= 0x0000) && (LA12_0 <= '!')) || ((LA12_0 >= '#') && (LA12_0 <= 0xFFFF))) ) 
        	    {
        	        alt12=1;
        	    }

        	}
        	switch (alt12) 
        	{
        	    case 1:
        	        // SMARTPL.g:161:13: ~ ( '\"' )
        	        {
        	            if ( ((LA(1) >= 0x0000) && (LA(1) <= '!')) || ((LA(1) >= '#') && (LA(1) <= 0xFFFF)) )
        	            {
        	                CONSUME();

        	            }
        	            else 
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();    goto ruleSTREx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt12 >= 1 )
        		{
        		    goto loop12;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleSTREx;
        	}
        	cnt12++;
            }
            loop12: ;	/* Jump to here if this rule does not match */
        }
        MATCHC('"'); 
        if  (HASEXCEPTION())
        {
            goto ruleSTREx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSTREx; /* Prevent compiler warnings */
    ruleSTREx: ;

}
// $ANTLR end STR

//   Comes from: 164:7: ( ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INT
 *
 * Looks to match the characters the constitute the token INT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINT(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INT;
       
    
    // SMARTPL.g:164:7: ( ( '0' .. '9' )+ )
    // SMARTPL.g:164:9: ( '0' .. '9' )+
    {
        // SMARTPL.g:164:9: ( '0' .. '9' )+
        {
            int cnt13=0;

            for (;;)
            {
                int alt13=2;
        	switch ( LA(1) ) 
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt13=1;
        		}
        	    break;

        	}

        	switch (alt13) 
        	{
        	    case 1:
        	        // SMARTPL.g:164:10: '0' .. '9'
        	        {
        	            MATCHRANGE('0', '9'); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleINTEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt13 >= 1 )
        		{
        		    goto loop13;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleINTEx;
        	}
        	cnt13++;
            }
            loop13: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleINTEx; /* Prevent compiler warnings */
    ruleINTEx: ;

}
// $ANTLR end INT

//   Comes from: 167:12: ( ( '\\t' | ' ' | '\\r' | '\\n' | '\\u000C' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WHITESPACE
 *
 * Looks to match the characters the constitute the token WHITESPACE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWHITESPACE(pSMARTPLLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WHITESPACE;
       
    
    // SMARTPL.g:167:12: ( ( '\\t' | ' ' | '\\r' | '\\n' | '\\u000C' ) )
    // SMARTPL.g:167:14: ( '\\t' | ' ' | '\\r' | '\\n' | '\\u000C' )
    {
        if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || ((LA(1) >= '\f') && (LA(1) <= '\r')) || LA(1) == ' ' )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleWHITESPACEEx;
        }

        {
             LEXSTATE->channel = HIDDEN; 
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleWHITESPACEEx; /* Prevent compiler warnings */
    ruleWHITESPACEEx: ;

}
// $ANTLR end WHITESPACE

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void 
mTokens(pSMARTPLLexer ctx)
{
    {
        //  SMARTPL.g:1:8: ( T__30 | T__31 | STRTAG | INTTAG | DATETAG | ENUMTAG | INCLUDES | IS | INTBOOL | AFTER | BEFORE | AGO | AND | OR | NOT | LPAR | RPAR | DATE | DATINTERVAL | ENUMVAL | STR | INT | WHITESPACE )
        
        ANTLR3_UINT32 alt14;

        alt14=23;

        switch ( LA(1) ) 
        {
        case '{':
        	{
        		alt14=1;
        	}
            break;
        case '}':
        	{
        		alt14=2;
        	}
            break;
        case 'a':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'l':
        		case 'r':
        			{
        				alt14=3;
        			}
        		    break;
        		case 'f':
        			{
        				alt14=10;
        			}
        		    break;
        		case 'g':
        			{
        				alt14=12;
        			}
        		    break;
        		case 'n':
        			{
        				alt14=13;
        			}
        		    break;
        		case 'u':
        			{
        				alt14=20;
        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 14;
        		    EXCEPTION->state        = 3;


        		    goto ruleTokensEx;
        		}

        	}
            break;
        case 't':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'i':
        			{
        				switch ( LA(3) ) 
        				{
        				case 't':
        					{
        						alt14=3;
        					}
        				    break;
        				case 'm':
        					{
        						alt14=5;
        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 14;
        				    EXCEPTION->state        = 28;


        				    goto ruleTokensEx;
        				}

        			}
        		    break;
        		case 'y':
        			{
        				alt14=3;
        			}
        		    break;
        		case 'o':
        			{
        				alt14=18;
        			}
        		    break;
        		case 'v':
        			{
        				alt14=20;
        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 14;
        		    EXCEPTION->state        = 4;


        		    goto ruleTokensEx;
        		}

        	}
            break;
        case 'g':
        	{
        		alt14=3;
        	}
            break;
        case 'c':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'o':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'm':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'p':
        							{
        								switch ( LA(5) ) 
        								{
        								case 'o':
        									{
        										alt14=3;
        									}
        								    break;
        								case 'i':
        									{
        										alt14=4;
        									}
        								    break;

        								default:
        								    CONSTRUCTEX();
        								    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        								    EXCEPTION->message      = (void *)"";
        								    EXCEPTION->decisionNum  = 14;
        								    EXCEPTION->state        = 42;


        								    goto ruleTokensEx;
        								}

        							}
        						    break;

        						default:
        						    CONSTRUCTEX();
        						    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        						    EXCEPTION->message      = (void *)"";
        						    EXCEPTION->decisionNum  = 14;
        						    EXCEPTION->state        = 39;


        						    goto ruleTokensEx;
        						}

        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 14;
        				    EXCEPTION->state        = 29;


        				    goto ruleTokensEx;
        				}

        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 14;
        		    EXCEPTION->state        = 6;


        		    goto ruleTokensEx;
        		}

        	}
            break;
        case 'p':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'a':
        			{
        				alt14=3;
        			}
        		    break;
        		case 'l':
        			{
        				alt14=4;
        			}
        		    break;
        		case 'i':
        		case 'o':
        			{
        				alt14=20;
        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 14;
        		    EXCEPTION->state        = 7;


        		    goto ruleTokensEx;
        		}

        	}
            break;
        case 'r':
        	{
        		alt14=4;
        	}
            break;
        case 'y':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'e':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'a':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'r':
        							{
        								switch ( LA(5) ) 
        								{
        								case 's':
        									{
        										alt14=19;
        									}
        								    break;

        								default:
        								    alt14=4;}

        							}
        						    break;

        						default:
        						    CONSTRUCTEX();
        						    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        						    EXCEPTION->message      = (void *)"";
        						    EXCEPTION->decisionNum  = 14;
        						    EXCEPTION->state        = 40;


        						    goto ruleTokensEx;
        						}

        					}
        				    break;
        				case 's':
        					{
        						alt14=18;
        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 14;
        				    EXCEPTION->state        = 30;


        				    goto ruleTokensEx;
        				}

        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 14;
        		    EXCEPTION->state        = 9;


        		    goto ruleTokensEx;
        		}

        	}
            break;
        case 'd':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'a':
        			{
        				switch ( LA(3) ) 
        				{
        				case 't':
        					{
        						alt14=6;
        					}
        				    break;
        				case 'y':
        					{
        						alt14=19;
        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 14;
        				    EXCEPTION->state        = 31;


        				    goto ruleTokensEx;
        				}

        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 14;
        		    EXCEPTION->state        = 10;


        		    goto ruleTokensEx;
        		}

        	}
            break;
        case 'm':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'e':
        			{
        				alt14=6;
        			}
        		    break;
        		case 'o':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'n':
        					{
        						alt14=19;
        					}
        				    break;
        				case 'v':
        					{
        						alt14=20;
        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 14;
        				    EXCEPTION->state        = 33;


        				    goto ruleTokensEx;
        				}

        			}
        		    break;
        		case 'u':
        			{
        				alt14=20;
        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 14;
        		    EXCEPTION->state        = 11;


        		    goto ruleTokensEx;
        		}

        	}
            break;
        case 'i':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'n':
        			{
        				alt14=7;
        			}
        		    break;
        		case 's':
        			{
        				alt14=8;
        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 14;
        		    EXCEPTION->state        = 12;


        		    goto ruleTokensEx;
        		}

        	}
            break;
        case '<':
        case '=':
        case '>':
        	{
        		alt14=9;
        	}
            break;
        case 'b':
        	{
        		alt14=11;
        	}
            break;
        case 'A':
        	{
        		alt14=13;
        	}
            break;
        case 'O':
        case 'o':
        	{
        		alt14=14;
        	}
            break;
        case 'N':
        case 'n':
        	{
        		alt14=15;
        	}
            break;
        case '(':
        	{
        		alt14=16;
        	}
            break;
        case ')':
        	{
        		alt14=17;
        	}
            break;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		switch ( LA(2) ) 
        		{
        		case '0':
        		case '1':
        		case '2':
        		case '3':
        		case '4':
        		case '5':
        		case '6':
        		case '7':
        		case '8':
        		case '9':
        			{
        				switch ( LA(3) ) 
        				{
        				case '0':
        				case '1':
        				case '2':
        				case '3':
        				case '4':
        				case '5':
        				case '6':
        				case '7':
        				case '8':
        				case '9':
        					{
        						switch ( LA(4) ) 
        						{
        						case '0':
        						case '1':
        						case '2':
        						case '3':
        						case '4':
        						case '5':
        						case '6':
        						case '7':
        						case '8':
        						case '9':
        							{
        								switch ( LA(5) ) 
        								{
        								case '-':
        									{
        										alt14=18;
        									}
        								    break;

        								default:
        								    alt14=22;}

        							}
        						    break;

        						default:
        						    alt14=22;}

        					}
        				    break;

        				default:
        				    alt14=22;}

        			}
        		    break;

        		default:
        		    alt14=22;}

        	}
            break;
        case 'l':
        	{
        		alt14=18;
        	}
            break;
        case 'w':
        	{
        		alt14=19;
        	}
            break;
        case 'f':
        case 's':
        case 'u':
        	{
        		alt14=20;
        	}
            break;
        case '"':
        	{
        		alt14=21;
        	}
            break;
        case '\t':
        case '\n':
        case '\f':
        case '\r':
        case ' ':
        	{
        		alt14=23;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 14;
            EXCEPTION->state        = 0;


            goto ruleTokensEx;
        }

        switch (alt14) 
        {
    	case 1:
    	    // SMARTPL.g:1:10: T__30
    	    {
    	        /* 1:10: T__30 */
    	        mT__30(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // SMARTPL.g:1:16: T__31
    	    {
    	        /* 1:16: T__31 */
    	        mT__31(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // SMARTPL.g:1:22: STRTAG
    	    {
    	        /* 1:22: STRTAG */
    	        mSTRTAG(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 4:
    	    // SMARTPL.g:1:29: INTTAG
    	    {
    	        /* 1:29: INTTAG */
    	        mINTTAG(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 5:
    	    // SMARTPL.g:1:36: DATETAG
    	    {
    	        /* 1:36: DATETAG */
    	        mDATETAG(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 6:
    	    // SMARTPL.g:1:44: ENUMTAG
    	    {
    	        /* 1:44: ENUMTAG */
    	        mENUMTAG(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 7:
    	    // SMARTPL.g:1:52: INCLUDES
    	    {
    	        /* 1:52: INCLUDES */
    	        mINCLUDES(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 8:
    	    // SMARTPL.g:1:61: IS
    	    {
    	        /* 1:61: IS */
    	        mIS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 9:
    	    // SMARTPL.g:1:64: INTBOOL
    	    {
    	        /* 1:64: INTBOOL */
    	        mINTBOOL(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 10:
    	    // SMARTPL.g:1:72: AFTER
    	    {
    	        /* 1:72: AFTER */
    	        mAFTER(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 11:
    	    // SMARTPL.g:1:78: BEFORE
    	    {
    	        /* 1:78: BEFORE */
    	        mBEFORE(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 12:
    	    // SMARTPL.g:1:85: AGO
    	    {
    	        /* 1:85: AGO */
    	        mAGO(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 13:
    	    // SMARTPL.g:1:89: AND
    	    {
    	        /* 1:89: AND */
    	        mAND(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 14:
    	    // SMARTPL.g:1:93: OR
    	    {
    	        /* 1:93: OR */
    	        mOR(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 15:
    	    // SMARTPL.g:1:96: NOT
    	    {
    	        /* 1:96: NOT */
    	        mNOT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 16:
    	    // SMARTPL.g:1:100: LPAR
    	    {
    	        /* 1:100: LPAR */
    	        mLPAR(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 17:
    	    // SMARTPL.g:1:105: RPAR
    	    {
    	        /* 1:105: RPAR */
    	        mRPAR(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 18:
    	    // SMARTPL.g:1:110: DATE
    	    {
    	        /* 1:110: DATE */
    	        mDATE(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 19:
    	    // SMARTPL.g:1:115: DATINTERVAL
    	    {
    	        /* 1:115: DATINTERVAL */
    	        mDATINTERVAL(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 20:
    	    // SMARTPL.g:1:127: ENUMVAL
    	    {
    	        /* 1:127: ENUMVAL */
    	        mENUMVAL(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 21:
    	    // SMARTPL.g:1:135: STR
    	    {
    	        /* 1:135: STR */
    	        mSTR(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 22:
    	    // SMARTPL.g:1:139: INT
    	    {
    	        /* 1:139: INT */
    	        mINT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 23:
    	    // SMARTPL.g:1:143: WHITESPACE
    	    {
    	        /* 1:143: WHITESPACE */
    	        mWHITESPACE(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;

        }
    }

    
    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */ 


/* End of code
 * =============================================================================
 */
