#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=15

start() {
	brctl addbr $BR_IF
	brctl setfd $BR_IF 0
	brctl stp $BR_IF 0
	echo 0 > /sys/devices/virtual/net/$BR_IF/bridge/multicast_snooping
}
