#!/bin/sh /etc/rc.common
START=99

KVER=`uname -r | cut -f 1`
MODULE_PATH=/lib/modules/$KVER

start() {
	# If WAN cable is disconnected try modem connection
	if [ "x$(detcable show | grep "WAN  : Plug off")" != "x" ]; then
		/sbin/rmmod NetUSB_02
		/sbin/insmod $MODULE_PATH/usbnet.ko
		/sbin/insmod $MODULE_PATH/cdc_ether.ko
		/sbin/insmod $MODULE_PATH/rndis_host.ko
		/sbin/usbmode

		# Check is modem attached
		/sbin/ifconfig eth2 up
		if [ $? -eq 0 ]; then
			/etc/init.d/net-wan stop
			/etc/init.d/detcable stop
			/etc/init.d/watchdog stop
			echo -n 1 > /tmp/port_status
			echo modem > /tmp/modem
			/etc/init.d/net-wan start
			/usr/sbin/net-wall restart
		else

		# No modem found, restore kernel objects
			/sbin/rmmod rndis_host
			/sbin/rmmod cdc_ether
			/sbin/rmmod usbnet
			/sbin/insmod $MODULE_PATH/NetUSB.ko
		fi
	fi
}
