#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org 

START=99
start() {
	[ -f /etc/sysctl.conf ] && sysctl -p >&-
	[ -d /etc/sysctl.d ] && \
		for i in /etc/sysctl.d/*.conf; do
			sysctl -p $i >&-
		done
	if [ "$($CONFIG get ap_mode)" = "1" ]; then
		echo "0" > /proc/sys/net/bridge/bridge-nf-call-iptables
                echo "0" > /proc/sys/quantenna/nss/enable
	fi
}
